In [1]:
from datetime import datetime

import pandas as pd
import plotly
import plotly.graph_objs as go
import simplejson as json

In [2]:
plotly.offline.init_notebook_mode(connected=True)

In [3]:
# Load our raw data into a Pandas DataFrame
with open('../data/transfocator.txt', 'r') as handle:
    df = pd.read_json(handle)

In [4]:
df

    finish_pos     finish_ts  start_pos      start_ts  success  target
0    121.00045  1.559844e+09  119.99680  1.559844e+09     True     121
1    125.00260  1.559844e+09  121.00045  1.559844e+09     True     125
2    111.00020  1.559844e+09  125.00260  1.559844e+09     True     111
3    124.00035  1.559844e+09  111.00020  1.559844e+09     True     124
4    104.00010  1.559844e+09  124.00035  1.559844e+09     True     104
5    107.00045  1.559844e+09  104.00010  1.559844e+09     True     107
6    106.00805  1.559844e+09  107.00045  1.559844e+09     True     106
7    109.99870  1.559844e+09  106.00805  1.559844e+09     True     110
8    101.00435  1.559844e+09  109.99870  1.559844e+09     True     101
9     99.99570  1.559844e+09  101.00435  1.559844e+09     True     100
10   110.99230  1.559844e+09   99.99570  1.559844e+09     True     111
11   116.00195  1.559844e+09  110.99230  1.559844e+09     True     116
12   116.99490  1.559844e+09  116.00195  1.559844e+09     True     117
13   107.99980  1.559844e+09  116.99490  1.559844e+09     True     108
14   101.00320  1.559844e+09  107.99980  1.559844e+09     True     101
15   106.00000  1.559844e+09  101.00320  1.559844e+09     True     106
16   123.99820  1.559844e+09  106.00000  1.559844e+09     True     124
17   107.00020  1.559844e+09  123.99820  1.559844e+09     True     107
18   107.99790  1.559844e+09  107.00020  1.559844e+09     True     108
19   116.99130  1.559844e+09  107.99790  1.559844e+09     True     117
20   118.00530  1.559844e+09  116.99130  1.559844e+09     True     118
21   108.99990  1.559844e+09  118.00530  1.559844e+09     True     109
22   112.99400  1.559844e+09  108.99990  1.559844e+09     True     113
23   117.99730  1.559844e+09  112.99400  1.559844e+09     True     118
24   101.00570  1.559844e+09  117.99730  1.559844e+09     True     101

In [5]:
data = [go.Scatter(
          # We have to convert our Python 
          x=[datetime.fromtimestamp(stamp) for stamp in df['start_ts']],
          y=df['start_pos'])]

plotly.offline.iplot(data)